### ISSUE TITLE
[Tracking] Additional features to be implemented - Vendor

### ISSUE THREAD

**Issue by anandprajapati1** [anandprajapati1/LunchOrderApp#4]
Features for Vendor -
- [x] Login as Vendor
- [x] View Orders - By vendor
- [x] Accept/Reject order - By vendor

**Comment by anandprajapati1** [comment]
Login complete and also added vendor dashboard view. functionality pending

**Comment by anandprajapati1** [comment]
Completed module - 
View Orders - Vendor
Accept/Reject order - Vendor

PR #11
