### ISSUE TITLE
[Tracking] - Business rules (USER)

### ISSUE THREAD

**Issue by anandprajapati1** [anandprajapati1/LunchOrderApp#7]
- [ ] Activation link for registration
- [ ] Cancel order (Once accepted by vendor, user should not be able to cancel order)
- [ ] Time restriction on place/repeat/cancel order
- [ ] Place order form > Remarks field -> change it to radio button
- [x] Place order - Card style layout
